// Database Schemas for the InvestmentStockTracker Google Sheet
// Default currency: INR (₹)
// Industry: IndustryId (PK), Name (Display Name)
// Stocks: StockId (PK), IndustryId / InduistryId (FK referencing Industry.IndustryId)
// Formulas: Liverate, closeyest, volume, 52WkHigh, 52WkLow, shares, changepct, eps, pe
// Exchange is derived from MktSymbol after removing Symbol.
// Purchases: PurchaseId (PK with template "Pur00000001"), StockId (FK referencing Stocks.StockId)

export interface Industry {
  IndustryId: string; // Primary Key (e.g. IND0001, IND0002)
  Name: string;       // Display Name (e.g. "Information Technology", "Banking & Finance")
}

export interface Stock {
  StockId: string;       // Primary Key (e.g. STK0001) - User customizable in Add Stock
  Symbol: string;        // Ticker symbol (e.g. RELIANCE, TCS, HDFCBANK)
  MktSymbol: string;     // Market Symbol (e.g. RELIANCE.NSE, TCS.NSE, INFY.BSE)
  CompanyName: string;   // Company name
  IndustryId: string;    // Foreign Key referencing Industry.IndustryId (also referred to as InduistryId)
  Sector?: string;       // Legacy sector / fallback
  Exchange: string;      // Derived from MktSymbol after removing Symbol (e.g. NSE, BSE)
  Liverate: number;      // Current live price from Google Sheet formula (=GOOGLEFINANCE)
  CurrentPrice: number;  // Current market price in INR (equals Liverate or fallback)
  CloseYest?: number;    // Yesterday's close price (closeyest formula)
  Volume?: number;       // Trading volume (volume formula)
  High52?: number;       // 52-week High (52WkHigh formula)
  Low52?: number;        // 52-week Low (52WkLow formula)
  SharesFormula?: number;// Aggregated shares from sheet formula (shares)
  ChangePct?: number;    // % change today (changepct formula)
  Eps?: number;          // Earnings per share (eps formula)
  Pe?: number;           // Price-to-Earnings ratio (pe formula)
  Currency: string;      // Default 'INR'
  DividendYield: number; // e.g. 0.85%
  LastUpdated: string;   // ISO timestamp
}

export interface Purchase {
  PurchaseId: string;    // Primary Key (Autogenerated template: Pur00000001)
  StockId: string;       // Foreign Key referencing Stocks.StockId
  PurchaseDate: string;  // ISO timestamp or Date string
  Quantity: number;      // Number of shares purchased
  PurchasePrice: number; // Price per share in INR
  TotalAmount: number;   // Quantity * PurchasePrice in INR
  Fees: number;          // Transaction/broker fees in INR
  Notes?: string;        // Notes/rationale
}

export interface Sale {
  SaleId: string;        // Primary Key (Autogenerated template: Sal00000001)
  SalesId: string;       // Primary Key (SalesId / SaleId)
  PurchaseId: string;    // Foreign Key referencing Purchases.PurchaseId
  StockId: string;       // Foreign Key referencing Stocks.StockId (derived via Purchases.StockId)
  SaleDate: string;      // ISO timestamp or Date string
  Quantity: number;      // Number of shares sold
  SalePrice: number;     // Selling price per share in INR (saved in Rate column of Sales sheet/table)
  Rate?: number;         // Rate column in Sales sheet/table
  TotalAmount: number;   // Gross Amount (Quantity * SalePrice) or Net Amount in INR
  Fees: number;          // Brokerage / STT / Transaction fees in INR
  Notes?: string;        // Notes/rationale
}

// Joined View Models
export interface EnrichedPurchase extends Purchase {
  stock?: Stock;
  symbol: string;        // Joined from Stocks.Symbol
  mktSymbol: string;     // Joined from Stocks.MktSymbol
  companyName: string;   // Joined from Stocks.CompanyName
  industryName: string;  // Joined from Industry.Name via Stocks.IndustryId
  sector: string;        // Sector or Industry Name
  exchange: string;      // Joined from Stocks.Exchange
  currentPrice: number;  // Joined from Stocks.Liverate or Stocks.CurrentPrice (INR)
  currentValue: number;  // RemainingQuantity * currentPrice (INR)
  gainLoss: number;      // CurrentValue - RemainingTotalCost (INR)
  gainLossPercent: number; // Gain / Cost * 100
  soldQuantity: number;  // Total shares sold from this specific Purchase lot
  remainingQuantity: number; // Quantity - soldQuantity
  isFullySold: boolean;  // remainingQuantity <= 0
}

export interface EnrichedSale extends Sale {
  stock?: Stock;
  purchase?: Purchase;
  symbol: string;        // Display Value joined from Stocks table (via Purchases.StockId -> Stocks.Symbol)
  mktSymbol: string;     // Joined from Stocks.MktSymbol
  companyName: string;   // Joined from Stocks.CompanyName
  industryName: string;  // Joined from Industry.Name
  exchange: string;      // Joined from Stocks.Exchange
  purchasePrice: number; // Original purchase price from Purchases lot
  purchaseDate: string;  // Original purchase date
  grossAmount: number;   // Quantity * SalePrice
  netAmount: number;     // grossAmount - Fees
  costBasis: number;     // Quantity * purchasePrice
  realizedGainLoss: number; // netAmount - costBasis
  realizedGainLossPercent: number; // (realizedGainLoss / costBasis) * 100
  rate?: number;         // Rate column
}

export interface EnrichedStock extends Stock {
  industryName: string;         // Joined from Industry.Name
  totalQuantity: number;        // Active remaining quantity owned (Purchased - Sold)
  totalPurchasedQuantity: number; // Total shares purchased
  totalSoldQuantity: number;    // Total shares sold
  totalInvested: number;        // Sum of TotalAmount from Purchases with this StockId (INR)
  activeCostBasis: number;      // Remaining shares * avg purchase price
  averagePurchasePrice: number; // TotalInvested / TotalPurchasedQuantity (INR)
  currentHoldingValue: number;  // TotalQuantity * Liverate (INR)
  unrealizedGainLoss: number;   // CurrentHoldingValue - ActiveCostBasis (INR)
  unrealizedGainLossPercent: number;
  realizedGainLoss: number;     // Total realized profit/loss from sales of this stock
  purchaseCount: number;        // Number of purchases for this stock
  saleCount: number;            // Number of sales for this stock
  allocationPercent?: number;   // % of total portfolio market value
}

/**
 * Derives the exchange name from MktSymbol after removing Symbol.
 * Example: MktSymbol "RELIANCE.NSE" and Symbol "RELIANCE" -> "NSE"
 * Example: MktSymbol "INFY:BSE" and Symbol "INFY" -> "BSE"
 * Example: MktSymbol "TCS.NS" and Symbol "TCS" -> "NSE"
 */
export function deriveExchangeFromMktSymbol(mktSymbol: string, symbol: string): string {
  if (!mktSymbol) return 'NSE';
  let remaining = mktSymbol.trim();
  if (symbol && symbol.trim()) {
    const escaped = symbol.trim().replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    remaining = remaining.replace(new RegExp(escaped, 'i'), '');
  }
  // Strip delimiters like '.', ':', '-', '_', and spaces
  const cleaned = remaining.replace(/^[.:\-_\s]+|[.:\-_\s]+$/g, '').trim().toUpperCase();
  if (cleaned === 'NS') return 'NSE';
  if (cleaned === 'BO') return 'BSE';
  return cleaned || 'NSE';
}

/**
 * Formats a currency amount in Indian Rupees (INR, ₹)
 */
export function formatINR(amount: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 2,
    minimumFractionDigits: 2,
  }).format(amount);
}

/**
 * Autogenerates the next PurchaseId using the template "Pur00000001"
 * Examples: Pur00000001, Pur00000002, Pur00000003...
 */
export function generatePurchaseId(existingPurchases: Purchase[]): string {
  let maxId = 0;
  const regex = /^(?:Pur|Purchase|Purchases)?(\d+)$/i;

  for (const p of existingPurchases) {
    const rawId = (p.PurchaseId || (p as any).PurchasesId || (p as any).purchaseid || '').toString().trim();
    if (rawId) {
      const match = rawId.match(regex);
      if (match) {
        const num = parseInt(match[1], 10);
        if (!isNaN(num) && num > maxId) {
          maxId = num;
        }
      } else {
        const digits = rawId.replace(/\D/g, '');
        if (digits) {
          const num = parseInt(digits, 10);
          if (!isNaN(num) && num > maxId) {
            maxId = num;
          }
        }
      }
    }
  }

  const nextId = maxId + 1;
  return `Pur${String(nextId).padStart(8, '0')}`;
}

/**
 * Autogenerates the next SaleId using the template "Sal00000001"
 * Supports Sal00000001, Sale00000001, Sales00000001, etc.
 */
export function generateSaleId(existingSales: Sale[]): string {
  let maxId = 0;
  const regex = /^(?:Sal|Sale|Sales)?(\d+)$/i;

  for (const s of existingSales) {
    const rawId = (s.SaleId || s.SalesId || (s as any).saleid || (s as any).salesid || (s as any)['Sale Id'] || (s as any)['Sales Id'] || '').toString().trim();
    if (rawId) {
      const match = rawId.match(regex);
      if (match) {
        const num = parseInt(match[1], 10);
        if (!isNaN(num) && num > maxId) {
          maxId = num;
        }
      } else {
        const digits = rawId.replace(/\D/g, '');
        if (digits) {
          const num = parseInt(digits, 10);
          if (!isNaN(num) && num > maxId) {
            maxId = num;
          }
        }
      }
    }
  }

  const nextId = maxId + 1;
  return `Sal${String(nextId).padStart(8, '0')}`;
}

export const generateSalesId = generateSaleId;

/**
 * Ensures a date string or Date object is returned in pure Date format: "YYYY-MM-DD"
 */
export function formatDateOnly(dateInput?: string | Date | null): string {
  if (!dateInput) return new Date().toISOString().split('T')[0];
  if (typeof dateInput === 'string') {
    const trimmed = dateInput.trim();
    if (/^\d{4}-\d{2}-\d{2}$/.test(trimmed)) {
      return trimmed;
    }
    const firstPart = trimmed.split(/[T\s]/)[0];
    if (/^\d{4}-\d{2}-\d{2}$/.test(firstPart)) {
      return firstPart;
    }
  }
  const d = new Date(dateInput);
  if (isNaN(d.getTime())) {
    return new Date().toISOString().split('T')[0];
  }
  return d.toISOString().split('T')[0];
}

/**
 * Returns today's date formatted as "YYYY-MM-DD"
 */
export function getTodayDateOnly(): string {
  return new Date().toISOString().split('T')[0];
}

/**
 * Autogenerates the next StockId using template "STK0001"
 */
export function generateStockId(existingStocks: Stock[]): string {
  let maxId = 0;
  const regex = /^STK(\d+)$/i;

  for (const s of existingStocks) {
    if (s.StockId) {
      const match = s.StockId.match(regex);
      if (match) {
        const num = parseInt(match[1], 10);
        if (!isNaN(num) && num > maxId) {
          maxId = num;
        }
      }
    }
  }

  const nextId = maxId + 1;
  return `STK${String(nextId).padStart(4, '0')}`;
}

export interface SheetSchemaDefinition {
  title: string;
  headers: string[];
  sampleRows: (string | number)[][];
}

export const DEFAULT_INDUSTRIES: Industry[] = [
  { IndustryId: 'IND0001', Name: 'Energy & Telecom' },
  { IndustryId: 'IND0002', Name: 'Information Technology' },
  { IndustryId: 'IND0003', Name: 'Banking & Finance' },
  { IndustryId: 'IND0004', Name: 'Automotive' },
  { IndustryId: 'IND0005', Name: 'Consumer Goods (FMCG)' },
  { IndustryId: 'IND0006', Name: 'Engineering & Infrastructure' },
  { IndustryId: 'IND0007', Name: 'Pharmaceuticals & Healthcare' },
  { IndustryId: 'IND0008', Name: 'Metals & Mining' },
  { IndustryId: 'IND0009', Name: 'Real Estate & Construction' }
];

export const INVESTMENT_SHEET_SCHEMAS: SheetSchemaDefinition[] = [
  {
    title: 'Industry',
    headers: ['IndustryId', 'Name'],
    sampleRows: [
      ['IND0001', 'Energy & Telecom'],
      ['IND0002', 'Information Technology'],
      ['IND0003', 'Banking & Finance'],
      ['IND0004', 'Automotive'],
      ['IND0005', 'Consumer Goods (FMCG)'],
      ['IND0006', 'Engineering & Infrastructure'],
      ['IND0007', 'Pharmaceuticals & Healthcare'],
      ['IND0008', 'Metals & Mining'],
      ['IND0009', 'Real Estate & Construction']
    ]
  },
  {
    title: 'Stocks',
    headers: [
      'StockId', 
      'Symbol', 
      'MktSymbol', 
      'CompanyName', 
      'IndustryId', 
      'Exchange', 
      'Liverate', 
      'closeyest', 
      'volume', 
      '52WkHigh', 
      '52WkLow', 
      'shares', 
      'changepct', 
      'eps', 
      'pe', 
      'Currency', 
      'DividendYield', 
      'LastUpdated'
    ],
    sampleRows: [
      [
        'STK0001', 'RELIANCE', 'RELIANCE.NSE', 'Reliance Industries Ltd.', 'IND0001', 'NSE',
        '=IFERROR(GOOGLEFINANCE(C2,"price"),2980.50)',
        '=IFERROR(GOOGLEFINANCE(C2,"closeyest"),2965.00)',
        '=IFERROR(GOOGLEFINANCE(C2,"volume"),4500000)',
        '=IFERROR(GOOGLEFINANCE(C2,"high52"),3217.90)',
        '=IFERROR(GOOGLEFINANCE(C2,"low52"),2220.30)',
        '=IFERROR(SUMIFS(Purchases!D:D,Purchases!B:B,A2),20)',
        '=IFERROR(GOOGLEFINANCE(C2,"changepct"),0.52)',
        '=IFERROR(GOOGLEFINANCE(C2,"eps"),102.50)',
        '=IFERROR(GOOGLEFINANCE(C2,"pe"),29.07)',
        'INR', 0.35, getTodayDateOnly()
      ],
      [
        'STK0002', 'TCS', 'TCS.NSE', 'Tata Consultancy Services Ltd.', 'IND0002', 'NSE',
        '=IFERROR(GOOGLEFINANCE(C3,"price"),4250.00)',
        '=IFERROR(GOOGLEFINANCE(C3,"closeyest"),4215.00)',
        '=IFERROR(GOOGLEFINANCE(C3,"volume"),1800000)',
        '=IFERROR(GOOGLEFINANCE(C3,"high52"),4592.25)',
        '=IFERROR(GOOGLEFINANCE(C3,"low52"),3313.00)',
        '=IFERROR(SUMIFS(Purchases!D:D,Purchases!B:B,A3),15)',
        '=IFERROR(GOOGLEFINANCE(C3,"changepct"),0.83)',
        '=IFERROR(GOOGLEFINANCE(C3,"eps"),128.40)',
        '=IFERROR(GOOGLEFINANCE(C3,"pe"),33.10)',
        'INR', 1.15, getTodayDateOnly()
      ],
      [
        'STK0003', 'HDFCBANK', 'HDFCBANK.NSE', 'HDFC Bank Ltd.', 'IND0003', 'NSE',
        '=IFERROR(GOOGLEFINANCE(C4,"price"),1640.25)',
        '=IFERROR(GOOGLEFINANCE(C4,"closeyest"),1648.00)',
        '=IFERROR(GOOGLEFINANCE(C4,"volume"),7200000)',
        '=IFERROR(GOOGLEFINANCE(C4,"high52"),1794.00)',
        '=IFERROR(GOOGLEFINANCE(C4,"low52"),1363.55)',
        '=IFERROR(SUMIFS(Purchases!D:D,Purchases!B:B,A4),35)',
        '=IFERROR(GOOGLEFINANCE(C4,"changepct"),-0.47)',
        '=IFERROR(GOOGLEFINANCE(C4,"eps"),85.20)',
        '=IFERROR(GOOGLEFINANCE(C4,"pe"),19.25)',
        'INR', 1.20, getTodayDateOnly()
      ],
      [
        'STK0004', 'INFY', 'INFY.NSE', 'Infosys Ltd.', 'IND0002', 'NSE',
        '=IFERROR(GOOGLEFINANCE(C5,"price"),1890.80)',
        '=IFERROR(GOOGLEFINANCE(C5,"closeyest"),1875.00)',
        '=IFERROR(GOOGLEFINANCE(C5,"volume"),3500000)',
        '=IFERROR(GOOGLEFINANCE(C5,"high52"),1991.45)',
        '=IFERROR(GOOGLEFINANCE(C5,"low52"),1358.35)',
        '=IFERROR(SUMIFS(Purchases!D:D,Purchases!B:B,A5),25)',
        '=IFERROR(GOOGLEFINANCE(C5,"changepct"),0.84)',
        '=IFERROR(GOOGLEFINANCE(C5,"eps"),63.15)',
        '=IFERROR(GOOGLEFINANCE(C5,"pe"),29.94)',
        'INR', 2.10, getTodayDateOnly()
      ],
      [
        'STK0005', 'ICICIBANK', 'ICICIBANK.NSE', 'ICICI Bank Ltd.', 'IND0003', 'NSE',
        '=IFERROR(GOOGLEFINANCE(C6,"price"),1220.40)',
        '=IFERROR(GOOGLEFINANCE(C6,"closeyest"),1212.00)',
        '=IFERROR(GOOGLEFINANCE(C6,"volume"),5100000)',
        '=IFERROR(GOOGLEFINANCE(C6,"high52"),1335.00)',
        '=IFERROR(GOOGLEFINANCE(C6,"low52"),928.00)',
        '=IFERROR(SUMIFS(Purchases!D:D,Purchases!B:B,A6),0)',
        '=IFERROR(GOOGLEFINANCE(C6,"changepct"),0.69)',
        '=IFERROR(GOOGLEFINANCE(C6,"eps"),59.80)',
        '=IFERROR(GOOGLEFINANCE(C6,"pe"),20.40)',
        'INR', 0.85, getTodayDateOnly()
      ],
      [
        'STK0006', 'TATAMOTORS', 'TATAMOTORS.NSE', 'Tata Motors Ltd.', 'IND0004', 'NSE',
        '=IFERROR(GOOGLEFINANCE(C7,"price"),975.60)',
        '=IFERROR(GOOGLEFINANCE(C7,"closeyest"),988.00)',
        '=IFERROR(GOOGLEFINANCE(C7,"volume"),4200000)',
        '=IFERROR(GOOGLEFINANCE(C7,"high52"),1179.05)',
        '=IFERROR(GOOGLEFINANCE(C7,"low52"),608.00)',
        '=IFERROR(SUMIFS(Purchases!D:D,Purchases!B:B,A7),50)',
        '=IFERROR(GOOGLEFINANCE(C7,"changepct"),-1.25)',
        '=IFERROR(GOOGLEFINANCE(C7,"eps"),82.40)',
        '=IFERROR(GOOGLEFINANCE(C7,"pe"),11.84)',
        'INR', 0.60, getTodayDateOnly()
      ],
      [
        'STK0007', 'ITC', 'ITC.BSE', 'ITC Ltd.', 'IND0005', 'BSE',
        '=IFERROR(GOOGLEFINANCE(C8,"price"),510.30)',
        '=IFERROR(GOOGLEFINANCE(C8,"closeyest"),506.00)',
        '=IFERROR(GOOGLEFINANCE(C8,"volume"),6800000)',
        '=IFERROR(GOOGLEFINANCE(C8,"high52"),528.50)',
        '=IFERROR(GOOGLEFINANCE(C8,"low52"),399.30)',
        '=IFERROR(SUMIFS(Purchases!D:D,Purchases!B:B,A8),100)',
        '=IFERROR(GOOGLEFINANCE(C8,"changepct"),0.85)',
        '=IFERROR(GOOGLEFINANCE(C8,"eps"),16.80)',
        '=IFERROR(GOOGLEFINANCE(C8,"pe"),30.37)',
        'INR', 2.75, getTodayDateOnly()
      ],
      [
        'STK0008', 'LT', 'LT.NSE', 'Larsen & Toubro Ltd.', 'IND0006', 'NSE',
        '=IFERROR(GOOGLEFINANCE(C9,"price"),3620.00)',
        '=IFERROR(GOOGLEFINANCE(C9,"closeyest"),3605.00)',
        '=IFERROR(GOOGLEFINANCE(C9,"volume"),1200000)',
        '=IFERROR(GOOGLEFINANCE(C9,"high52"),3948.60)',
        '=IFERROR(GOOGLEFINANCE(C9,"low52"),2873.35)',
        '=IFERROR(SUMIFS(Purchases!D:D,Purchases!B:B,A9),0)',
        '=IFERROR(GOOGLEFINANCE(C9,"changepct"),0.42)',
        '=IFERROR(GOOGLEFINANCE(C9,"eps"),94.60)',
        '=IFERROR(GOOGLEFINANCE(C9,"pe"),38.26)',
        'INR', 0.95, getTodayDateOnly()
      ]
    ]
  },
  {
    title: 'Purchases',
    headers: ['PurchaseId', 'StockId', 'PurchaseDate', 'Quantity', 'PurchasePrice', 'TotalAmount', 'Fees', 'Notes'],
    sampleRows: [
      ['Pur00000001', 'STK0001', '2025-01-15', 20, 2850.00, 57000.00, 20, 'Initial accumulation in Reliance'],
      ['Pur00000002', 'STK0002', '2025-01-20', 15, 3950.00, 59250.00, 20, 'IT sector core portfolio buy'],
      ['Pur00000003', 'STK0003', '2025-02-01', 35, 1580.00, 55300.00, 20, 'Private bank leader allocation'],
      ['Pur00000004', 'STK0004', '2025-02-18', 25, 1720.00, 43000.00, 20, 'Q3 results dip accumulation'],
      ['Pur00000005', 'STK0006', '2025-02-22', 50, 910.00, 45500.00, 20, 'EV transition long term hold'],
      ['Pur00000006', 'STK0007', '2025-03-05', 100, 480.00, 48000.00, 20, 'Defensive dividend stock allocation']
    ]
  },
  {
    title: 'Sales',
    headers: ['SalesId', 'PurchaseId', 'StockId', 'SaleDate', 'Quantity', 'Rate', 'TotalAmount', 'Fees', 'Notes'],
    sampleRows: [
      ['Sal00000001', 'Pur00000001', 'STK0001', '2025-02-10', 5, 2950.00, 14750.00, 20, 'Partial profit booking on Reliance']
    ]
  }
];
