import React, { useState, useEffect } from 'react';
import { ShoppingCart, Hash, X, CheckCircle2 } from 'lucide-react';
import { Stock, Purchase, generatePurchaseId, formatINR } from '../types/database';

interface PurchaseModalProps {
  isOpen: boolean;
  onClose: () => void;
  stocks: Stock[];
  purchases: Purchase[];
  initialStockId?: string;
  onRequestSubmit: (purchase: {
    StockId: string;
    Quantity: number;
    PurchasePrice: number;
    TotalAmount: number;
    Fees: number;
    Notes: string;
    PurchaseId?: string;
  }) => Promise<void>;
}

export const PurchaseModal: React.FC<PurchaseModalProps> = ({
  isOpen,
  onClose,
  stocks,
  purchases,
  initialStockId,
  onRequestSubmit,
}) => {
  const [selectedStockId, setSelectedStockId] = useState<string>('');
  const [quantity, setQuantity] = useState<string>('10');
  const [purchasePrice, setPurchasePrice] = useState<string>('1500.00');
  const [fees, setFees] = useState<string>('20.00');
  const [notes, setNotes] = useState<string>('');
  const [isSubmitting, setIsSubmitting] = useState<boolean>(false);

  // Next autogenerated PurchaseId
  const nextPurchaseId = generatePurchaseId(purchases);

  // Set initial selected stock
  useEffect(() => {
    if (stocks.length > 0) {
      const defaultStock = (initialStockId && stocks.find(s => s.StockId === initialStockId)) 
        ? initialStockId 
        : stocks[0].StockId;
      
      setSelectedStockId(defaultStock);
      const stockObj = stocks.find(s => s.StockId === defaultStock);
      if (stockObj) {
        const livePrice = stockObj.Liverate > 0 ? stockObj.Liverate : stockObj.CurrentPrice;
        setPurchasePrice(livePrice.toFixed(2));
      }
    }
  }, [stocks, initialStockId, isOpen]);

  if (!isOpen) return null;

  const currentSelectedStock = stocks.find(s => s.StockId === selectedStockId);

  const handleStockChange = (stockId: string) => {
    setSelectedStockId(stockId);
    const stockObj = stocks.find(s => s.StockId === stockId);
    if (stockObj) {
      const livePrice = stockObj.Liverate > 0 ? stockObj.Liverate : stockObj.CurrentPrice;
      setPurchasePrice(livePrice.toFixed(2));
    }
  };

  const numQuantity = parseFloat(quantity) || 0;
  const numPrice = parseFloat(purchasePrice) || 0;
  const numFees = parseFloat(fees) || 0;
  const calculatedTotal = (numQuantity * numPrice) + numFees;

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!selectedStockId || numQuantity <= 0 || numPrice <= 0 || isSubmitting) {
      return;
    }

    setIsSubmitting(true);
    try {
      await onRequestSubmit({
        StockId: selectedStockId,
        Quantity: numQuantity,
        PurchasePrice: numPrice,
        TotalAmount: calculatedTotal,
        Fees: numFees,
        Notes: notes || `Purchase of ${currentSelectedStock?.Symbol || selectedStockId}`,
        PurchaseId: nextPurchaseId,
      });
      onClose();
    } catch (err) {
      console.error('Save error:', err);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in duration-150">
      <div className="w-full max-w-lg bg-slate-900 border border-slate-700/80 rounded-t-3xl sm:rounded-2xl shadow-2xl p-4 sm:p-6 relative max-h-[92vh] flex flex-col">
        <div className="flex items-center justify-between pb-4 border-b border-slate-800 shrink-0">
          <div className="flex items-center gap-3">
            <div className="p-2 sm:p-2.5 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-xl">
              <ShoppingCart className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base sm:text-lg font-bold text-white tracking-tight">
                Record Stock Purchase
              </h2>
              <p className="text-xs text-slate-400">
                Add shares to your holdings ledger
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            disabled={isSubmitting}
            className="text-slate-400 hover:text-white p-2 rounded-xl hover:bg-slate-800 disabled:opacity-50 min-h-[44px] min-w-[44px] flex items-center justify-center cursor-pointer"
            aria-label="Close"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Autogenerated Purchase ID badge */}
        <div className="my-3 sm:my-4 p-3 rounded-xl bg-slate-950/80 border border-slate-800 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2 text-xs text-slate-300">
            <Hash className="w-4 h-4 text-emerald-400" />
            <span className="font-medium">Purchase ID</span>
          </div>
          <span className="px-2.5 py-1 text-xs font-mono font-bold bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 rounded-lg">
            {nextPurchaseId}
          </span>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4 overflow-y-auto flex-1">
          {/* Stock Selection */}
          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1.5 flex items-center justify-between">
              <span>Stock</span>
              {currentSelectedStock && (
                <span className="text-cyan-400 font-mono text-[11px]">
                  {currentSelectedStock.Exchange}
                </span>
              )}
            </label>
            <select
              value={selectedStockId}
              onChange={e => handleStockChange(e.target.value)}
              className="w-full min-h-[44px] bg-slate-950 border border-slate-700/80 rounded-xl px-3.5 py-2.5 text-base sm:text-xs text-white font-medium focus:outline-none focus:border-cyan-500"
            >
              {stocks.map((stock, idx) => (
                <option key={`${stock.StockId}_${idx}`} value={stock.StockId}>
                  {stock.Symbol} — {stock.CompanyName} ({formatINR(stock.Liverate > 0 ? stock.Liverate : stock.CurrentPrice)})
                </option>
              ))}
            </select>
          </div>

          {/* Numeric Inputs: Quantity & Purchase Price */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                Quantity (Shares)
              </label>
              <input
                type="number"
                step="any"
                min="0.0001"
                required
                value={quantity}
                onChange={e => setQuantity(e.target.value)}
                placeholder="e.g. 25"
                className="w-full min-h-[44px] bg-slate-950 border border-slate-700/80 rounded-xl px-3.5 py-2.5 text-base sm:text-sm text-white focus:outline-none focus:border-cyan-500 font-mono font-bold"
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                Purchase Price (₹ INR)
              </label>
              <input
                type="number"
                step="any"
                min="0.01"
                required
                value={purchasePrice}
                onChange={e => setPurchasePrice(e.target.value)}
                placeholder="0.00"
                className="w-full min-h-[44px] bg-slate-950 border border-slate-700/80 rounded-xl px-3.5 py-2.5 text-base sm:text-sm text-white focus:outline-none focus:border-cyan-500 font-mono font-bold"
              />
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                Fees / Charges (₹ INR)
              </label>
              <input
                type="number"
                step="any"
                min="0"
                value={fees}
                onChange={e => setFees(e.target.value)}
                placeholder="20.00"
                className="w-full min-h-[44px] bg-slate-950 border border-slate-700/80 rounded-xl px-3.5 py-2.5 text-base sm:text-sm text-white focus:outline-none focus:border-cyan-500 font-mono"
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-300 mb-1.5">
                Total Amount (₹ INR)
              </label>
              <div className="w-full min-h-[44px] bg-slate-950 border border-slate-700/80 rounded-xl px-3.5 py-2.5 text-base sm:text-sm font-bold text-emerald-400 font-mono flex items-center">
                {formatINR(calculatedTotal)}
              </div>
            </div>
          </div>

          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1.5">
              Notes (Optional)
            </label>
            <input
              type="text"
              value={notes}
              onChange={e => setNotes(e.target.value)}
              placeholder="e.g. DCA order, long-term buy"
              className="w-full min-h-[44px] bg-slate-950 border border-slate-700/80 rounded-xl px-3.5 py-2.5 text-base sm:text-xs text-white focus:outline-none focus:border-cyan-500"
            />
          </div>

          {/* Form Actions */}
          <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-800">
            <button
              type="button"
              onClick={onClose}
              disabled={isSubmitting}
              className="px-4 py-2.5 min-h-[44px] text-xs font-semibold text-slate-300 hover:text-white bg-slate-800 hover:bg-slate-700 rounded-xl transition cursor-pointer touch-manipulation"
            >
              Cancel
            </button>
            <button
              type="submit"
              disabled={isSubmitting}
              className="px-5 py-2.5 min-h-[44px] text-xs font-bold rounded-xl text-white bg-emerald-600 hover:bg-emerald-500 shadow-lg shadow-emerald-950/40 transition flex items-center justify-center gap-2 disabled:opacity-50 cursor-pointer touch-manipulation"
            >
              {isSubmitting ? (
                <>
                  <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  <span>Recording...</span>
                </>
              ) : (
                <>
                  <CheckCircle2 className="w-4 h-4 text-emerald-200" />
                  <span>Record Purchase</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
